# Generated by Django 2.0.5 on 2018-06-03 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TwentyUI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
